<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

    <title>Video Poker</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap.min.css') ?>" media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css') ?>" media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/game.css') ?>" media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/account-movements.css') ?>" media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/store.css') ?>" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body class="home">
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top headroom">
        <div class="container">
            <a href="<?= URL::toRoute('auth/login') ?>">
                <div class="navbar-header">
                    <!-- Button for smallest screens -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <img src="<?= Asset::image('logo.png')?>" class="navbar-brand">
                </div>
            </a>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <?php if (isset($_SESSION['user'])) { $user = User::find($_SESSION['user']->id); ?>
                        <!-- User is logged in -->
                        <li class="active"><a href="<?= URL::toRoute('game/') ?>" id="play-btn">Play</a></li>
                        <li class="active"><a href="<?= URL::toRoute('game/rules') ?>">Game Rules</a></li>
                        <li class="active"><a href="<?= URL::toRoute('game/ranking') ?>">Top Players</a></li>
                        <li class="dropdown active">
                            <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                                <span><?= $user->fullname . ' (' ?></span>
                                <span id="user-credits"><?= $user->balance ?></span>
                                <span><?= 'credits )' ?></span>
                                <b class='caret'></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= URL::toRoute('user/profile') ?>">My Profile</a></li>
                                <li><a href="<?= URL::toRoute('account/movements') ?>">Account Movements</a></li>
                                <li><a href="<?= URL::toRoute('store/') ?>">Buy Credits</a></li>
                            </ul>
                        </li>
                        <li><a href="/video-poker/app/auth/logout" class="btn">Log Out</a></li>
                    <?php } else { ?>
                        <!-- User is a guest -->
                        <li class="active"><a href="<?= URL::toRoute('game/rules') ?>">Game Rules</a></li>
                        <li class="active"><a href="<?= URL::toRoute('game/ranking') ?>">Top Players</a></li>
                        <li><a href="<?= URL::toRoute('auth/login') ?>" class="btn">Log In</a></li>
                    <?php } ?>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
    <!-- /.navbar -->
    <header id="head" class="secondary"></header>

    <script>
        const playButton = document.querySelector('#play-btn');
        const userCredits = parseInt(document.querySelector('#user-credits').textContent);

        function goToGame() {
            if (userCredits > 0) {
                // enough credits
                window.location.href = '/video-poker/app/game';
            } else {
                // not enough credits
                alert('You don\'t have enough credits. We\'ll send you to our store, so you can buy some credits and play.');
                window.location.href = '/video-poker/app/store';               
            }
        }
        
        if (! window.location.href.includes('/video-poker/app/store')) {
            playButton.addEventListener('click', goToGame);
        }
    </script>