<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

$user  = Data::get('user');

if (isset($_SESSION['bet'])) {
    $bet = $_SESSION['bet'];
}
if (isset($_SESSION['hand'])) {
    $hand = $_SESSION['hand'];
}

Layout::includeLayout('header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <main id="game">
                <!-- Points System -->
                <section>
                    <table class="table table-bordered">
                        <thead>
                            <th>Hands</th>
                            <?php 
                            for ($i = 1; $i < 6; $i++) { 
                                if (isset($bet) && ($i == $bet)) { ?>
                                    <th class="bet">Bet x<?= $i ?></th>
                                <?php } else { ?>
                                    <th>Bet x<?= $i ?></th>
                                <?php } ?>
                            <?php } ?>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Royal Flush</td>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) {
                                    if ($i == 5) {
                                        $x+= 3000;
                                    } else {
                                        $x+= 250;
                                    }
                                    if (isset($bet) && ($i == $bet)) {
                                ?>
                                    <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>
                                    <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>Straight Flush</td>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=50; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>4 Of A Kind</td>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=30; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>Full House</th>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=6; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>Flush</th>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=5; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>Straight</th>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=4; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>3 Of A Kind</th>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=3; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>Two Pair</th>
                                <?php 
                                $x = 0; 
                                for ($i = 1; $i < 6; $i++) { 
                                    $x+=2; 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $x ?></td>
                                    <?php } else { ?>                                
                                <td><?= $x ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                            <tr>
                                <td>Jacks Of Better</th>
                                <?php 
                                for ($i = 1; $i < 6; $i++) { 
                                    if (isset($bet) && ($i == $bet)) { ?>
                                        <td class="bet"><?= $i ?></td>
                                    <?php } else { ?>                                
                                <td><?= $i ?></td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                        </tbody>
                    </table>
                </section>

                <!-- Cards -->
                <section id="cards">
                    <?php if (strpos($_SERVER['REQUEST_URI'], '/hand')) { ?>
                    <h3> Select the cards you want to fold</h3>
                    <br>
                    <?php } ?>
                    <?php 
                    if (isset($hand) && count($hand) == 5) {
                        for ($card = 0; $card < 5; $card++) {
                    ?>
                    <img id="<?= $card ?>" src="<?= $hand[$card] ?>">
                        <?php } ?>
                    <?php } else { ?>
                    <img id="1" src="<?= Asset::image('cards/back/cardBack_red5.png')?>">
                    <img id="2" src="<?= Asset::image('cards/back/cardBack_red5.png')?>">
                    <img id="3" src="<?= Asset::image('cards/back/cardBack_red5.png')?>">
                    <img id="4" src="<?= Asset::image('cards/back/cardBack_red5.png')?>">
                    <img id="5" src="<?= Asset::image('cards/back/cardBack_red5.png')?>">
                    <?php } ?>
                </section>

                <!-- Game Actions -->
                <footer>
                    <?php 
                    for ($i = 1; $i < 6; $i++) {                         
                        if ($user->balance >= $i) { ?>
                        <button class="bet-btn">Bet x<?= $i ?></button>
                        <?php } ?>
                    <?php } ?>
                    <?php if (strpos($_SERVER['REQUEST_URI'], '/hand')) { ?>
                    <a href="#">
                        <button class="deal-btn" onclick="drawCards()">Draw cards</button>
                    </a>
                    <?php } elseif (strpos($_SERVER['REQUEST_URI'], '/prize')) { ?>
                    <a href="<?= URL::toRoute('game/') ?>">
                        <button class="deal-btn">Play again</button>
                    </a>                                        
                    <?php } else { ?>
                    <button class="deal-btn" onclick="dealCards()">Deal cards</button>                    
                    <?php } ?>
                </footer>
            </main>
        </div>
    </div>
</div>

<script src="<?= Asset::js('game.js')?>"></script>

<?php Layout::includeLayout('footer'); ?>
*/