<?php 

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$user = Data::get('user');

Layout::includeLayout('header') ?>

<!-- container -->
<div class="container">

	<div class="row">

		<!-- Article main content -->
		<article class="col-xs-12 maincontent">
			<header class="page-header">
				<h1 class="page-title">
					<?php
					if ($user->id) { 
						echo 'Edit Profile';
					} else { 
						echo 'Register'; 
					}
					?>
				</h1>
			</header>

			<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3 class="thin text-center"></h3>

						<?php if ($user->id) { ?>
						<form method="post" action="<?= URL::toRoute('user/update') ?>">
						<?php } else { ?>
						<form method="post" action="<?= URL::toRoute('user/store') ?>">
						<?php } ?>
							<div class="top-margin bg-danger text-center error_register"></div>
							<div class="top-margin">
								<label for="fullName">
                                    Full Name <span class="text-danger">*</span>
                                </label>
								<?php if ($user->id) { ?>
								<input type="text" class="form-control" id="fullName" name="fullName" value="<?= $user->fullname ?>">
								<?php } else { ?>
								<input type="text" class="form-control" id="fullName" name="fullName" required>
								<?php } ?>
							</div>
							<!-- Error Message -->
							<?php if (isset($_SESSION['fullNameError'])) { ?>
							<div class="error-message">
								<?= $_SESSION['fullNameError'] ?>
							</div>
							<?php } ?>

							<?php if (! $user->id) { ?>
							<div class="top-margin">
								<label for="birthday">
                                    Birthday <span class="text-danger">*</span>
                                </label>
								<input type="date" class="form-control" id="birthday" name="birthday" required>
							</div>
							<!-- Error Message -->							
							<div class="error-message">
							</div>
							<?php } ?>

							<?php if (! $user->id) { ?>
							<div class="top-margin">
								<label for="username">
                                    Username <span class="text-danger">*</span>
                                </label>
								<input type="text" class="form-control" id="username" name="username" required>
							</div>
							<!-- Error Message -->							
							<div class="error-message">
							</div>
							<?php } ?>
							
							<div class="top-margin">
								<label for="email">
                                    Email <span class="text-danger">*</span>
                                </label>
								<?php if ($user->id) { ?>
								<input type="email" class="form-control" id="email" name="email" value="<?= $user->email ?>">
								<?php } else { ?>
								<input type="email" class="form-control" id="email" name="email" required>
								<?php } ?>
							</div>
							<!-- Error Message -->							
							<?php if (isset($_SESSION['emailError'])) { ?>
							<div class="error-message">
								<?= $_SESSION['emailError'] ?>
							</div>
							<?php } ?>
							
							<div class="top-margin">
								<label for="password">
                                    Password <span class="text-danger">*</span>
                                </label>
								<?php if ($user->id) { ?>
								<input type="password" class="form-control" id="password" name="password">
								<?php } else { ?>
								<input type="password" class="form-control" id="password" name="password" required>
								<?php } ?>
							</div>
							<!-- Error Message -->							
							<?php if (isset($_SESSION['passwordError'])) { ?>
							<div class="error-message">
								<?= $_SESSION['passwordError'] ?>
							</div>
							<?php } ?>

							<hr>

							<div class="row">
								<div class="col-lg-4 text-left">
									<button class="btn btn-action" type="submit">
										<?php
										if ($user->id) { 
											echo 'Save';
										}
										else { 
											echo 'Submit'; 
										}
										?>
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>

			</div>

		</article>
		<!-- /Article -->

	</div>
</div>
<!-- /container -->

<?php Layout::includeLayout('footer') ?>
*/