<?php 

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;


Layout::includeLayout('header') ?>

<!-- container -->
<div class="container">

	<div class="row">

		<!-- Article main content -->
		<article class="col-xs-12 maincontent">
			<header class="page-header">
				<h1 class="page-title">Log in</h1>
			</header>

			<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3 class="thin text-center">Log in to your account</h3>
						<hr>

						<form method="post" action="<?= URL::toRoute('auth/authenticate') ?>">
							<div class="top-margin bg-danger text-center error_register">
							</div>
							<div class="top-margin">
								<label for="username">
									Username <span class="text-danger">*</span>
								</label>
								<input type="text" class="form-control" id="username" name="username" value="med" required>
							</div>
							<div class="top-margin">
								<label for="password">
									Password <span class="text-danger">*</span>
								</label>
								<input type="password" class="form-control" id="password" name="password" value="secret" required>
							</div>

							<hr>

							<div class="row">
								<div class="col-lg-8">
									<b><a href="">Forgot password?</a></b>
								</div>
								<div class="col-lg-4 text-right">
									<button class="btn btn-action" type="submit">Log in</button>
								</div>
							</div>
						</form>
					</div>
				</div>

			</div>

		</article>
		<!-- /Article -->

	</div>
</div>
<!-- /container -->

<?php Layout::includeLayout('footer') ?>