<?php 

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$loginFailed   = Data::get('loginFailed');
$userIsBlocked = Data::get('userIsBlocked');

Layout::includeLayout('header') ?>

<!-- container -->
<div class="container">

	<div class="row">

		<!-- Article main content -->
		<article class="col-xs-12 maincontent">
			<header class="page-header">
				<h1 class="page-title">Log in</h1>
			</header>

			<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3 class="thin text-center">Log in to your account</h3>
						
						<hr>

						<?php if ($loginFailed == 'true') { ?>
							<div class="top-margin bg-danger text-center error_register" style="padding: 15px;">
								<i class="fa fa-warning fa-l"></i><b> Error </b><i class="fa fa-warning fa-l"></i>
								<br>The username or password is incorrect.
							</div>
						<?php } elseif ($userIsBlocked == 'true') { ?>
							<div class="top-margin bg-danger text-center error_register" style="padding: 15px;">
								<i class="fa fa-warning fa-l"></i><b> Error </b><i class="fa fa-warning fa-l"></i>
								<br>The account you're trying to access has been banned or suspended.
							</div>
						<?php } ?>
						
						<form method="post" action="<?= URL::toRoute('auth/authenticate') ?>">
							<div class="top-margin bg-danger text-center error_register">
							</div>
							<div class="top-margin">
								<label for="username">
									Username <span class="text-danger">*</span>
								</label>
								<input type="text" class="form-control" id="username" name="username" required>
							</div>
							<div class="top-margin">
								<label for="password">
									Password <span class="text-danger">*</span>
								</label>
								<!--<input type="password" class="form-control" id="password" name="password" value="secret" required>-->
								<input type="password" class="form-control" id="password" name="password" required>
							</div>

							<hr>

							<footer style="display: flex; justify-content: space-between;">
								<div><button class="btn btn-action" type="submit">Log in</button></div>
								<div>
									<a href="<?= URL::toRoute('user/register') ?>">
										<button class="btn btn-secondary" type="button">Register</button>
									</a>
								</div>
							</footer>
						</form>
					</div>
				</div>

			</div>

		</article>
		<!-- /Article -->

	</div>
</div>
<!-- /container -->

<?php Layout::includeLayout('footer') ?>